# Generated by Django 5.2 on 2025-05-09 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crafters', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('companyname', models.TextField(blank=True)),
                ('slogan', models.TextField(blank=True)),
                ('aboutus', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='ContactUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FirstName', models.TextField(blank=True)),
                ('LastName', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='WebsiteReviews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review', models.TextField()),
            ],
        ),
    ]
