# Generated by Django 5.2.10 on 2026-02-02 08:10

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crafters', '0002_admindetails_contactus_websitereviews'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='added_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='admindetails',
            name='aboutus',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='admindetails',
            name='companyname',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='admindetails',
            name='slogan',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='contactus',
            name='FirstName',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='contactus',
            name='LastName',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
